-- Maps table seeds here (Example)
INSERT INTO maps (name, description, creator_id )         VALUES ('Abigails Amazing Attractions', 'these are all the amazing spots that I recommend. Hope to see you there!', 1);
INSERT INTO maps (name, description, creator_id )         VALUES ('Calvins Cool Creation', 'Wow, just discovered this cool app! Check out this map I made!', 2);
INSERT INTO maps (name, description, creator_id )         VALUES ('Declans Dearest Destinations', 'Wow, just made this cool map! Check it out to see my favourite libraries around the neighborhood.', 3);
INSERT INTO maps (name, description, creator_id)          VALUES ('Toronto','Idk what to say eh?', 4);
INSERT INTO maps (name, description, creator_id)          VALUES ('Toronto # 2','Idk what to say eh?', 4);
INSERT INTO maps (name, description, creator_id)          VALUES ('Montreal Eats','I am a super basic description. Cry at my mightiness!', 1);
INSERT INTO maps (name, description, creator_id)          VALUES ('Montreal2','I am a super basic description. Cry at my mightiness!', 1);
INSERT INTO maps (name, description, creator_id)          VALUES ('Montreal3','I am a super basic description. Cry at my mightiness!', 1);
INSERT INTO maps (name, description, creator_id)          VALUES ('Montreal4','I am a super basic description. Cry at my mightiness!', 1);
INSERT INTO maps (name, description, creator_id)          VALUES ('Montreal5','I am a super basic description. Cry at my mightiness!', 1);
INSERT INTO maps (name, description, creator_id)          VALUES ('Montreal6','I am a super basic description. Cry at my mightiness!', 1);
INSERT INTO maps (name, description, creator_id)          VALUES ('Montreal7','I am a super basic description. Cry at my mightiness!', 1);
INSERT INTO maps (name, description, creator_id)          VALUES ('Vancouver','I am a super basic description. Cry at my mightiness!', 2);
INSERT INTO maps (name, description, creator_id)          VALUES ('Vancouver1','I am a super basic description. Cry at my mightiness!', 2);
INSERT INTO maps (name, description, creator_id)          VALUES ('Vancouver2','I am a super basic description. Cry at my mightiness!', 2);
INSERT INTO maps (name, description, creator_id)          VALUES ('Vancouver3','I am a super basic description. Cry at my mightiness!', 2);
INSERT INTO maps (name, description, creator_id)          VALUES ('Vancouver4','I am a super basic description. Cry at my mightiness!', 2);
INSERT INTO maps (name, description, creator_id)          VALUES ('Vancouver5','I am a super basic description. Cry at my mightiness!', 2);
INSERT INTO maps (name, description, creator_id)          VALUES ('Ottawa','I am a super basic description. Cry at my mightiness!', 3);
INSERT INTO maps (name, description, creator_id)          VALUES ('Ottawa2','I am a super basic description. Cry at my mightiness!', 3);
INSERT INTO maps (name, description, creator_id)          VALUES ('Ottawa3','I am a super basic description. Cry at my mightiness!', 3);
INSERT INTO maps (name, description, creator_id)          VALUES ('Ottawa4','I am a super basic description. Cry at my mightiness!', 3);
INSERT INTO maps (name, description, creator_id)          VALUES ('Ottawa5','I am a super basic description. Cry at my mightiness!', 3);
INSERT INTO maps (name, description, creator_id)          VALUES ('Ottawa6','I am a super basic description. Cry at my mightiness!', 3);
INSERT INTO maps (name, description, creator_id)          VALUES ('Ottawa7','I am a super basic description. Cry at my mightiness!', 3);
INSERT INTO maps (name, description, creator_id,  active) VALUES ('Montreal','I am a super basic description. Cry at my mightiness!', 1, FALSE);
