-- Points table seeds here (Example)
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('The Royal Exemplary Park', 'The forest was limitless, light, and lush. Its canopy was demanded by spruce, chestnut, and maple, sufficient twinkling lights bursted through their crowns for scattered saplings to take advantage of the nut and seed covered grounds below.', 'https://i.imgur.com/V6UPvSu.jpeg', -79.38, 43.65, 1);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('The Regenerative Public Gardens', 'Curling branches hung from a couple of trees, and a mishmash of flowers, which were found in the most quiet places, stood out against the otherwise brown terrain.', 'https://i.imgur.com/V6UPvSu.jpeg', -79.397507, 43.664002, 1);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('The Permaculture Fungal Gardens', 'The forest was endless, radiant, and primal. Its canopy was eclipsed by cypress, magnolia, and oak, their crowns allowed for short beams of light to descend for an overabundance of bushes to sprout', 'https://i.imgur.com/V6UPvSu.jpeg', -79.356480, 43.661021, 1);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('The Agricultural Conservatory of Irolin', 'A discord of sounds, belonging mostly to rummaging critters, resonated through the air, and drowned out the raging river currents clashing against boulders.', 'https://i.imgur.com/V6UPvSu.jpeg', -79.422398, 43.668348, 1);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('The Esthon Botanical Garden', 'There were fields uninterrupted for as far as the eye could see. All around you horses and cows frolicked and loitered in the verdant pastures, and passing field after field ran a mossy, cobblestone road.', 'https://i.imgur.com/V6UPvSu.jpeg', -79.346867, 43.673190, 1);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('The Confection Connection', 'Ten broad, square towers form a protective barrier all around the castle and are connected by fairly low, solid walls made of black stone.', 'https://i.imgur.com/5tQsEPU.jpeg', 2.294481, 48.858372, 2);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('Tough Cookies', 'where that epic thing happened that one time', 'https://i.imgur.com/V6UPvSu.jpeg', 2.327385, 48.865807, 2);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('Cakey Bakey', 'Stylish windows are scattered here and there around the walls in fairly symmetrical patterns, along with huge crenelations for archers and artillery.', 'https://i.imgur.com/zDEs51F.jpeg', 2.273483, 48.874388, 2);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('Midnight Brewers', 'I remember an epic thing happened HERE last tuesday.', 'https://i.imgur.com/V6UPvSu.jpeg', 133.785496, -25.261463, 3);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('The Celestial Brewing Company', 'Well kept gardens with fragrant flowers, gorgeous trees and many bushes decorate the outside', 'https://i.imgur.com/V6UPvSu.jpeg', 133.792791, -25.262899, 3);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('Dark Horse Brewery', 'I remember an epic thing happened HERE last tuesday.', 'https://i.imgur.com/V6UPvSu.jpeg', 133.790388, -25.263287, 3);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('Cackling Hyena Brewing Co.', 'I remember an epic thing happened HERE last tuesday.', 'https://i.imgur.com/V6UPvSu.jpeg', 133.783607, -25.259949, 3);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('Epic Location 4', 'this place has really great food!', 'https://i.imgur.com/5tQsEPU.jpeg', -79.33, 43.67, 4);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('Epic Location 4', 'this place has really great food!', 'https://i.imgur.com/5tQsEPU.jpeg', -79.33, 43.67, 5);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('Epic Location 4', 'this place has really great food!', 'https://i.imgur.com/5tQsEPU.jpeg', -79.33, 43.67, 6);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('Epic Location 4', 'this place has really great food!', 'https://i.imgur.com/5tQsEPU.jpeg', -79.33, 43.67, 7);
INSERT INTO points (name, description, img_url, longitude, latitude, map_id)  VALUES ('Epic Location 4', 'this place has really great food!', 'https://i.imgur.com/5tQsEPU.jpeg', -79.33, 43.67, 8);
